---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install docker
    yum: name=docker state=present
  - name: Start docker
    service: name=docker state=started
  - name: Get the dockerfile
    git: repo=https://github.com/omarmansor/Jenkins-Ansible-Demo.git dest=/tmp/dockerdir
  - name: Build the dockerfile
    command: chdir=/tmp/dockerdir docker build -t deploy:ansible .
  - name: Run the docker image
    command: docker run -itd -P deploy:ansible
